{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-postgresql
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}